In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('arrests.csv')
#if the data is in an excel file
df_xlsx = pd.read_excel('arrests.xlsx')
#if the data is in a text format,specify a delimiter(something which is separating the data)
df = pd.read_csv('arrests.txt',delimiter='\t')

In [9]:
print(df.head(5))
#bottom rows
print(df.tail(5))

   Unnamed: 0 released colour  year  age     sex employed citizen  checks
0           1      Yes  White  2002   21    Male      Yes     Yes       3
1           2       No  Black  1999   17    Male      Yes     Yes       3
2           3      Yes  White  2000   24    Male      Yes     Yes       3
3           4       No  Black  2000   46    Male      Yes     Yes       1
4           5      Yes  Black  1999   27  Female      Yes     Yes       1
      Unnamed: 0 released colour  year  age     sex employed citizen  checks
5221        5222      Yes  White  2000   17    Male      Yes     Yes       0
5222        5223      Yes  White  2000   21  Female      Yes     Yes       0
5223        5224      Yes  Black  1999   21  Female      Yes     Yes       1
5224        5225       No  Black  1998   24    Male      Yes     Yes       4
5225        5226      Yes  White  1999   16    Male      Yes     Yes       3

Read the data nicely in pandas

In [17]:
#read headers
print(df.columns)
#read each column
print(df['citizen'][0:3])
#or
print(df.citizen)
#if we want to access different columns of data
print(df[['citizen','colour','age']])
#read each row
print(df.head(3))
#read a specifically indexed row
print(df.iloc[2:6])
#read a specific location(row,column)
print(df.iloc[2,4])
#find specific data
df =df.loc[(df['released']=='Yes') or (df['age']==17 )]

Index(['Unnamed: 0', 'released', 'released', 'released', 'released',
       'released', 'released', 'released', 'released', 'released',
       ...
       'released', 'released', 'released', 'released', 'released', 'released',
       'released', 'released', 'released', 'released'],
      dtype='object', length=3025)

KeyError: 'citizen'

In [29]:
#iterate over a row
for index,row in df.iterrows():
 print(index,row['colour'])

0 White
1 Black
2 White
3 Black
4 Black
5 Black
6 White
7 White
8 Black
9 White
10 White
11 White
12 White
13 Black
14 Black
15 White
16 White
17 White
18 White
19 White
20 White
21 White
22 White
23 White
24 White
25 White
26 Black
27 White
28 White
29 White
30 White
31 White
32 White
33 White
34 White
35 White
36 White
37 White
38 Black
39 White
40 White
41 Black
42 White
43 White
44 White
45 White
46 White
47 White
48 White
49 Black
50 Black
51 Black
52 White
53 White
54 White
55 White
56 White
57 Black
58 White
59 White
60 Black
61 White
62 Black
63 Black
64 White
65 White
66 White
67 White
68 Black
69 Black
70 White
71 White
72 Black
73 White
74 Black
75 White
76 Black
77 White
78 White
79 White
80 White
81 Black
82 White
83 White
84 Black
85 White
86 White
87 White
88 White
89 Black
90 White
91 White
92 Black
93 White
94 White
95 White
96 Black
97 White
98 White
99 White
100 White
101 White
102 White
103 White
104 White
105 White
106 White
107 White
108 White
109 White
110 White
111 White
112 White
113 Black
114 White
115 White
116 White
117 White
118 White
119 White
120 Black
121 White
122 Black
123 Black
124 White
125 White
126 White
127 White
128 White
129 Black
130 Black
131 Black
132 White
133 White
134 White
135 White
136 White
137 White
138 Black
139 White
140 White
141 Black
142 Black
143 White
144 White
145 White
146 Black
147 White
148 White
149 Black
150 Black
151 White
152 White
153 White
154 White
155 White
156 White
157 White
158 White
159 White
160 White
161 White
162 White
163 White
164 White
165 Black
166 Black
167 Black
168 White
169 White
170 White
171 White
172 White
173 White
174 Black
175 White
176 White
177 White
178 White
179 White
180 White
181 White
182 Black
183 White
184 Black
185 White
186 White
187 White
188 White
189 White
190 White
191 White
192 White
193 Black
194 Black
195 White
196 White
197 Black
198 White
199 White
200 White
201 Black
202 White
203 Black
204 White
205 White
206 White
207 White
208 Black
209 White
210 White
211 White
212 White
213 White
214 White
215 White
216 White
217 White
218 White
219 Black
220 White
221 White
222 White
223 Black
224 White
225 White
226 White
227 White
228 Black
229 White
230 Black
231 White
232 White
233 White
234 Black
235 White
236 White
237 Black
238 White
239 White
240 White
241 Black
242 White
243 Black
244 White
245 White
246 White
247 Black
248 White
249 Black
250 White
251 White
252 White
253 White
254 Black
255 White
256 White
257 White
258 White
259 White
260 Black
261 White
262 White
263 White
264 White
265 White
266 White
267 White
268 Black
269 White
270 White
271 White
272 White
273 White
274 White
275 White
276 Black
277 Black
278 White
279 Black
280 White
281 Black
282 White
283 White
284 Black
285 White
286 White
287 White
288 White
289 Black
290 White
291 Black
292 Black
293 White
294 White
295 Black
296 White
297 White
298 Black
299 White
300 Black
301 Black
302 White
303 White
304 White
305 White
306 White
307 White
308 White
309 White
310 White
311 White
312 Black
313 White
314 White
315 White
316 White
317 White
318 White
319 White
320 White
321 White
322 White
323 White
324 White
325 Black
326 White
327 White
328 White
329 White
330 White
331 Black
332 White
333 White
334 Black
335 White
336 White
337 Black
338 White
339 Black
340 White
341 Black
342 White
343 White
344 White
345 Black
346 White
347 White
348 White
349 White
350 White
351 White
352 White
353 White
354 White
355 White
356 White
357 White
358 Black
359 Black
360 White
361 White
362 Black
363 White
364 White
365 White
366 White
367 White
368 White
369 White
370 White
371 Black
372 Black
373 White
374 White
375 Black
376 White
377 White
378 Black
379 Black
380 White
381 White
382 White
383 White
384 White
385 Black
386 White
387 White
388 White
389 White
390 White
391 White
392 White
393 White
394 White
395 White
396 White
397 White
398 White
399 White
400 White
401 White
402 White
403 Black
404 Black
405 White
406 White
407 White
408 Black
409 White
410 White
411 Black
412 White
413 White
414 White
415 Black
416 White
417 White
418 White
419 White
420 White
421 Black
422 White
423 White
424 White
425 White
426 White
427 White
428 White
429 White
430 White
431 White
432 White
433 White
434 White
435 White
436 White
437 White
438 White
439 White
440 White
441 White
442 White
443 White
444 Black
445 Black
446 White
447 White
448 White
449 White
450 Black
451 Black
452 White
453 White
454 White
455 Black
456 White
457 White
458 White
459 White
460 White
461 White
462 White
463 White
464 Black
465 Black
466 White
467 Black
468 White
469 White
470 Black
471 White
472 White
473 White
474 White
475 White
476 White
477 White
478 White
479 White
480 White
481 Black
482 White
483 White
484 White
485 Black
486 White
487 White
488 Black
489 White
490 Black
491 Black
492 White
493 Black
494 White
495 White
496 Black
497 White
498 White
499 Black
500 White
501 White
502 White
503 White
504 White
505 White
506 White
507 White
508 White
509 White
510 White
511 White
512 White
513 White
514 White
515 White
516 White
517 White
518 White
519 Black
520 Black
521 Black
522 Black
523 White
524 White
525 Black
526 White
527 White
528 White
529 White
530 White
531 White
532 Black
533 White
534 White
535 White
536 White
537 White
538 White
539 White
540 Black
541 White
542 Black
543 Black
544 White
545 White
546 Black
547 White
548 White
549 Black
550 White
551 White
552 Black
553 White
554 White
555 White
556 White
557 White
558 White
559 White
560 White
561 Black
562 White
563 White
564 White
565 White
566 White
567 White
568 White
569 White
570 White
571 White
572 Black
573 White
574 White
575 White
576 White
577 White
578 White
579 White
580 White
581 White
582 White
583 Black
584 White
585 White
586 Black
587 White
588 White
589 White
590 Black
591 Black
592 Black
593 White
594 Black
595 White
596 Black
597 Black
598 White
599 Black
600 White
601 White
602 Black
603 White
604 White
605 White
606 White
607 White
608 White
609 White
610 White
611 White
612 White
613 White
614 White
615 White
616 White
617 White
618 White
619 White
620 White
621 White
622 White
623 White
624 Black
625 Black
626 Black
627 White
628 Black
629 Black
630 Black
631 White
632 White
633 White
634 White
635 Black
636 White
637 White
638 Black
639 White
640 White
641 White
642 White
643 White
644 White
645 White
646 Black
647 White
648 White
649 White
650 White
651 White
652 Black
653 White
654 White
655 White
656 White
657 White
658 White
659 Black
660 Black
661 White
662 White
663 White
664 White
665 White
666 Black
667 Black
668 White
669 White
670 White
671 White
672 White
673 White
674 White
675 White
676 Black
677 White
678 Black
679 White
680 White
681 White
682 White
683 Black
684 Black
685 White
686 Black
687 White
688 White
689 White
690 White
691 Black
692 White
693 White
694 White
695 Black
696 White
697 White
698 White
699 White
700 White
701 White
702 White
703 White
704 White
705 White
706 White
707 Black
708 White
709 White
710 White
711 White
712 White
713 White
714 White
715 Black
716 White
717 White
718 Black
719 White
720 White
721 Black
722 White
723 White
724 White
725 White
726 White
727 White
728 Black
729 White
730 White
731 Black
732 White
733 White
734 White
735 White
736 White
737 White
738 White
739 White
740 Black
741 Black
742 Black
743 White
744 White
745 White
746 White
747 White
748 White
749 White
750 White
751 Black
752 White
753 White
754 White
755 White
756 White
757 White
758 White
759 Black
760 Black
761 White
762 Black
763 White
764 Black
765 White
766 White
767 White
768 White
769 White
770 White
771 White
772 White
773 White
774 White
775 White
776 Black
777 White
778 White
779 White
780 White
781 White
782 White
783 White
784 Black
785 White
786 Black
787 White
788 Black
789 White
790 Black
791 Black
792 Black
793 White
794 White
795 White
796 Black
797 White
798 White
799 White
800 White
801 Black
802 Black
803 White
804 White
805 White
806 White
807 White
808 White
809 Black
810 Black
811 White
812 White
813 Black
814 Black
815 White
816 White
817 White
818 White
819 White
820 White
821 White
822 White
823 White
824 White
825 White
826 White
827 Black
828 White
829 White
830 White
831 White
832 White
833 White
834 White
835 White
836 White
837 White
838 White
839 Black
840 Black
841 White
842 White
843 White
844 White
845 White
846 White
847 Black
848 White
849 White
850 White
851 White
852 Black
853 White
854 White
855 Black
856 Black
857 Black
858 White
859 White
860 White
861 White
862 White
863 White
864 White
865 White
866 White
867 White
868 White
869 White
870 White
871 White
872 White
873 White
874 White
875 Black
876 White
877 Black
878 White
879 White
880 White
881 White
882 Black
883 Black
884 Black
885 White
886 White
887 White
888 White
889 White
890 White
891 White
892 White
893 White
894 Black
895 Black
896 White
897 Black
898 Black
899 White
900 Black
901 White
902 White
903 Black
904 White
905 White
906 White
907 Black
908 White
909 White
910 Black
911 White
912 White
913 Black
914 Black
915 White
916 White
917 White
918 White
919 Black
920 White
921 Black
922 White
923 White
924 White
925 White
926 White
927 White
928 White
929 White
930 Black
931 White
932 White
933 White
934 White
935 White
936 White
937 White
938 White
939 Black
940 White
941 White
942 Black
943 White
944 White
945 White
946 White
947 Black
948 White
949 White
950 Black
951 White
952 Black
953 White
954 White
955 White
956 Black
957 Black
958 White
959 White
960 White
961 White
962 Black
963 Black
964 White
965 Black
966 Black
967 White
968 Black
969 White
970 White
971 White
972 White
973 White
974 White
975 White
976 White
977 White
978 White
979 White
980 White
981 White
982 Black
983 Black
984 White
985 White
986 Black
987 White
988 White
989 White
990 White
991 White
992 White
993 White
994 White
995 White
996 White
997 Black
998 White
999 White
1000 White
1001 White
1002 White
1003 White
1004 White
1005 White
1006 White
1007 White
1008 White
1009 White
1010 White
1011 Black
1012 White
1013 White
1014 Black
1015 White
1016 White
1017 White
1018 White
1019 Black
1020 White
1021 White
1022 White
1023 White
1024 White
1025 White
1026 White
1027 Black
1028 White
1029 White
1030 White
1031 White
1032 White
1033 White
1034 White
1035 Black
1036 Black
1037 White
1038 White
1039 White
1040 White
1041 White
1042 Black
1043 Black
1044 White
1045 Black
1046 White
1047 White
1048 White
1049 White
1050 White
1051 White
1052 White
1053 White
1054 White
1055 White
1056 White
1057 White
1058 Black
1059 White
1060 Black
1061 Black
1062 White
1063 White
1064 Black
1065 Black
1066 White
1067 White
1068 Black
1069 Black
1070 Black
1071 White
1072 Black
1073 White
1074 White
1075 Black
1076 White
1077 White
1078 Black
1079 White
1080 White
1081 White
1082 White
1083 Black
1084 Black
1085 Black
1086 White
1087 White
1088 White
1089 White
1090 White
1091 White
1092 White
1093 White
1094 White
1095 White
1096 White
1097 White
1098 White
1099 Black
1100 White
1101 White
1102 White
1103 Black
1104 White
1105 White
1106 Black
1107 White
1108 Black
1109 White
1110 White
1111 White
1112 White
1113 White
1114 White
1115 White
1116 Black
1117 White
1118 White
1119 Black
1120 Black
1121 White
1122 White
1123 Black
1124 White
1125 White
1126 White
1127 White
1128 White
1129 Black
1130 White
1131 Black
1132 White
1133 White
1134 Black
1135 Black
1136 Black
1137 White
1138 White
1139 White
1140 White
1141 Black
1142 White
1143 White
1144 White
1145 Black
1146 Black
1147 White
1148 White
1149 White
1150 Black
1151 White
1152 White
1153 Black
1154 White
1155 White
1156 White
1157 White
1158 White
1159 White
1160 White
1161 White
1162 Black
1163 White
1164 White
1165 White
1166 White
1167 White
1168 Black
1169 White
1170 White
1171 White
1172 White
1173 Black
1174 White
1175 Black
1176 White
1177 White
1178 White
1179 White
1180 Black
1181 White
1182 White
1183 White
1184 White
1185 Black
1186 Black
1187 White
1188 Black
1189 White
1190 White
1191 Black
1192 White
1193 White
1194 White
1195 White
1196 White
1197 White
1198 White
1199 White
1200 White
1201 White
1202 Black
1203 White
1204 Black
1205 White
1206 White
1207 White
1208 White
1209 White
1210 Black
1211 Black
1212 White
1213 White
1214 White
1215 White
1216 White
1217 White
1218 White
1219 White
1220 White
1221 White
1222 White
1223 White
1224 White
1225 Black
1226 White
1227 White
1228 Black
1229 White
1230 White
1231 Black
1232 White
1233 White
1234 White
1235 White
1236 White
1237 White
1238 White
1239 White
1240 White
1241 Black
1242 White
1243 White
1244 White
1245 White
1246 Black
1247 White
1248 White
1249 White
1250 White
1251 White
1252 White
1253 Black
1254 White
1255 White
1256 White
1257 White
1258 White
1259 White
1260 White
1261 White
1262 White
1263 Black
1264 White
1265 White
1266 White
1267 White
1268 Black
1269 White
1270 Black
1271 White
1272 White
1273 White
1274 White
1275 White
1276 White
1277 Black
1278 White
1279 White
1280 White
1281 White
1282 Black
1283 White
1284 White
1285 White
1286 White
1287 White
1288 White
1289 White
1290 White
1291 White
1292 White
1293 White
1294 Black
1295 White
1296 White
1297 White
1298 Black
1299 White
1300 Black
1301 Black
1302 White
1303 White
1304 Black
1305 White
1306 Black
1307 White
1308 White
1309 White
1310 White
1311 White
1312 White
1313 White
1314 White
1315 White
1316 Black
1317 Black
1318 Black
1319 White
1320 Black
1321 White
1322 White
1323 White
1324 Black
1325 White
1326 White
1327 Black
1328 Black
1329 White
1330 White
1331 White
1332 White
1333 White
1334 Black
1335 Black
1336 White
1337 White
1338 White
1339 Black
1340 White
1341 White
1342 White
1343 White
1344 White
1345 White
1346 White
1347 White
1348 Black
1349 White
1350 Black
1351 Black
1352 White
1353 Black
1354 White
1355 Black
1356 White
1357 Black
1358 White
1359 White
1360 White
1361 White
1362 White
1363 Black
1364 White
1365 Black
1366 Black
1367 Black
1368 Black
1369 White
1370 White
1371 White
1372 White
1373 White
1374 White
1375 White
1376 White
1377 White
1378 White
1379 White
1380 Black
1381 Black
1382 White
1383 White
1384 Black
1385 White
1386 White
1387 White
1388 White
1389 White
1390 Black
1391 Black
1392 Black
1393 White
1394 White
1395 White
1396 White
1397 White
1398 White
1399 White
1400 Black
1401 White
1402 White
1403 Black
1404 Black
1405 Black
1406 White
1407 White
1408 White
1409 White
1410 White
1411 White
1412 White
1413 Black
1414 White
1415 White
1416 White
1417 Black
1418 White
1419 White
1420 White
1421 White
1422 White
1423 White
1424 White
1425 White
1426 Black
1427 Black
1428 Black
1429 Black
1430 White
1431 White
1432 White
1433 White
1434 White
1435 White
1436 White
1437 White
1438 Black
1439 White
1440 White
1441 White
1442 White
1443 White
1444 White
1445 White
1446 White
1447 White
1448 White
1449 White
1450 White
1451 White
1452 White
1453 Black
1454 White
1455 White
1456 White
1457 White
1458 White
1459 White
1460 White
1461 Black
1462 White
1463 White
1464 Black
1465 Black
1466 White
1467 Black
1468 Black
1469 White
1470 White
1471 White
1472 White
1473 White
1474 White
1475 White
1476 Black
1477 Black
1478 White
1479 Black
1480 Black
1481 Black
1482 Black
1483 White
1484 White
1485 White
1486 White
1487 White
1488 White
1489 Black
1490 Black
1491 White
1492 White
1493 Black
1494 White
1495 White
1496 White
1497 White
1498 White
1499 Black
1500 White
1501 White
1502 Black
1503 White
1504 Black
1505 White
1506 White
1507 White
1508 White
1509 White
1510 White
1511 White
1512 White
1513 White
1514 White
1515 White
1516 White
1517 White
1518 White
1519 Black
1520 Black
1521 White
1522 Black
1523 White
1524 White
1525 White
1526 White
1527 Black
1528 Black
1529 White
1530 White
1531 White
1532 White
1533 White
1534 White
1535 Black
1536 White
1537 White
1538 Black
1539 Black
1540 White
1541 White
1542 White
1543 White
1544 White
1545 White
1546 White
1547 White
1548 White
1549 White
1550 White
1551 Black
1552 White
1553 Black
1554 White
1555 White
1556 Black
1557 White
1558 White
1559 White
1560 Black
1561 White
1562 White
1563 White
1564 White
1565 Black
1566 White
1567 White
1568 Black
1569 White
1570 White
1571 White
1572 White
1573 White
1574 Black
1575 Black
1576 Black
1577 White
1578 White
1579 Black
1580 White
1581 White
1582 White
1583 White
1584 Black
1585 White
1586 Black
1587 Black
1588 Black
1589 Black
1590 White
1591 White
1592 White
1593 White
1594 White
1595 White
1596 White
1597 White
1598 White
1599 White
1600 White
1601 Black
1602 White
1603 White
1604 White
1605 White
1606 White
1607 White
1608 Black
1609 Black
1610 White
1611 White
1612 White
1613 Black
1614 Black
1615 White
1616 Black
1617 White
1618 White
1619 White
1620 White
1621 White
1622 White
1623 White
1624 White
1625 White
1626 White
1627 White
1628 White
1629 Black
1630 White
1631 White
1632 White
1633 White
1634 Black
1635 Black
1636 Black
1637 White
1638 Black
1639 Black
1640 White
1641 White
1642 White
1643 Black
1644 White
1645 Black
1646 White
1647 White
1648 White
1649 White
1650 White
1651 White
1652 White
1653 White
1654 White
1655 White
1656 White
1657 White
1658 White
1659 White
1660 Black
1661 White
1662 White
1663 White
1664 Black
1665 Black
1666 White
1667 White
1668 White
1669 White
1670 White
1671 White
1672 Black
1673 White
1674 White
1675 White
1676 White
1677 White
1678 Black
1679 White
1680 White
1681 White
1682 White
1683 White
1684 White
1685 White
1686 White
1687 White
1688 White
1689 White
1690 White
1691 White
1692 White
1693 White
1694 Black
1695 Black
1696 White
1697 Black
1698 White
1699 White
1700 White
1701 Black
1702 White
1703 White
1704 White
1705 White
1706 White
1707 Black
1708 White
1709 White
1710 White
1711 White
1712 White
1713 White
1714 White
1715 White
1716 White
1717 White
1718 White
1719 Black
1720 White
1721 Black
1722 White
1723 Black
1724 White
1725 Black
1726 Black
1727 Black
1728 White
1729 Black
1730 Black
1731 Black
1732 White
1733 White
1734 White
1735 Black
1736 White
1737 Black
1738 White
1739 White
1740 Black
1741 White
1742 Black
1743 White
1744 White
1745 Black
1746 Black
1747 White
1748 White
1749 White
1750 Black
1751 White
1752 White
1753 White
1754 White
1755 White
1756 Black
1757 White
1758 White
1759 White
1760 White
1761 White
1762 White
1763 Black
1764 White
1765 White
1766 White
1767 Black
1768 White
1769 White
1770 White
1771 Black
1772 White
1773 White
1774 White
1775 White
1776 White
1777 White
1778 Black
1779 White
1780 White
1781 Black
1782 White
1783 White
1784 White
1785 White
1786 Black
1787 Black
1788 White
1789 White
1790 White
1791 White
1792 White
1793 White
1794 White
1795 White
1796 White
1797 White
1798 Black
1799 White
1800 White
1801 White
1802 White
1803 White
1804 White
1805 White
1806 White
1807 Black
1808 Black
1809 White
1810 White
1811 White
1812 Black
1813 White
1814 White
1815 White
1816 White
1817 White
1818 Black
1819 White
1820 White
1821 White
1822 White
1823 White
1824 White
1825 White
1826 Black
1827 White
1828 Black
1829 White
1830 White
1831 Black
1832 White
1833 Black
1834 Black
1835 Black
1836 White
1837 Black
1838 White
1839 White
1840 Black
1841 Black
1842 White
1843 White
1844 Black
1845 White
1846 White
1847 White
1848 Black
1849 White
1850 White
1851 White
1852 White
1853 Black
1854 White
1855 White
1856 White
1857 White
1858 White
1859 Black
1860 White
1861 White
1862 White
1863 White
1864 Black
1865 White
1866 Black
1867 Black
1868 White
1869 White
1870 White
1871 White
1872 White
1873 White
1874 Black
1875 Black
1876 Black
1877 White
1878 White
1879 White
1880 White
1881 White
1882 White
1883 White
1884 White
1885 White
1886 White
1887 White
1888 Black
1889 Black
1890 White
1891 White
1892 White
1893 White
1894 White
1895 White
1896 Black
1897 White
1898 White
1899 White
1900 White
1901 White
1902 Black
1903 White
1904 Black
1905 White
1906 White
1907 White
1908 Black
1909 Black
1910 White
1911 Black
1912 White
1913 White
1914 Black
1915 White
1916 White
1917 White
1918 White

In [32]:
df.describe()

        Unnamed: 0         year          age       checks
count  5226.000000  5226.000000  5226.000000  5226.000000
mean   2613.500000  1999.509376    23.846537     1.636433
std    1508.760584     1.390056     8.316133     1.539230
min       1.000000  1997.000000    12.000000     0.000000
25%    1307.250000  1998.000000    18.000000     0.000000
50%    2613.500000  2000.000000    21.000000     1.000000
75%    3919.750000  2001.000000    27.000000     3.000000
max    5226.000000  2002.000000    66.000000     6.000000

In [34]:
df.sort_values('year',ascending = False)

      Unnamed: 0 released colour  year  age     sex employed citizen  checks
0              1      Yes  White  2002   21    Male      Yes     Yes       3
3062        3063      Yes  White  2002   15    Male      Yes     Yes       0
3041        3042      Yes  Black  2002   22    Male       No     Yes       0
1339        1340      Yes  Black  2002   16    Male      Yes     Yes       1
1623        1624      Yes  White  2002   19    Male       No     Yes       2
...          ...      ...    ...   ...  ...     ...      ...     ...     ...
3673        3674      Yes  White  1997   27    Male       No      No       3
1155        1156      Yes  White  1997   19    Male      Yes     Yes       0
3330        3331      Yes  White  1997   22  Female      Yes     Yes       0
4745        4746      Yes  Black  1997   41    Male      Yes      No       0
880          881      Yes  White  1997   32  Female       No     Yes       2

[5226 rows x 9 columns]

Making changes to the data

In [8]:
#adding a column
df['Year']= df['year']+df['age']
df.head(5)
#or
df['Total']=df.iloc[:,3:5].sum(axis=1)
#shift a column
cols = list(df.columns)
df=df[cols[0:4]+cols[-1]+cols[4:9]]
#deleting a column
df = df.drop(columns=['Year'])
df.head(5)

,Unnamed: 0,released,colour,year,age,sex,employed,citizen,checks,Total
0,1,Yes,White,2002,21,Male,Yes,Yes,3,<bound method NDFrame._add_numeric_operations....
1,2,No,Black,1999,17,Male,Yes,Yes,3,<bound method NDFrame._add_numeric_operations....
2,3,Yes,White,2000,24,Male,Yes,Yes,3,<bound method NDFrame._add_numeric_operations....
3,4,No,Black,2000,46,Male,Yes,Yes,1,<bound method NDFrame._add_numeric_operations....
4,5,Yes,Black,1999,27,Female,Yes,Yes,1,<bound method NDFrame._add_numeric_operations....

In [16]:
#save the new file
df.to_csv('modified.csv',index=False)

In [32]:
df.reset_index(drop=True , inplace = True)

In [33]:
df.loc[~df['Name'].str.contains('Mega')]

KeyError: 'Name'

In [34]:
#regular expressions
import re
#flags = re.I stands for ignore case
df.loc[df['type 1'].str.contains('fire|grass'),flags =re.I,regex=True]
#can also filter for words starting with a specific letter
str.contains('^pi[a-z]*')

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (305424042.py, line 4)

Conditional Changes

In [4]:
df.loc[df['year']>2000 , ['age','checks']] = 'Mind blown'
df
#they could be modified individually too ['mind blown','tramp']

,Unnamed: 0,released,colour,year,age,sex,employed,citizen,checks
0,1,Yes,White,2002,Mind blown,Male,Yes,Yes,Mind blown
1,2,No,Black,1999,17,Male,Yes,Yes,3
2,3,Yes,White,2000,24,Male,Yes,Yes,3
3,4,No,Black,2000,46,Male,Yes,Yes,1
4,5,Yes,Black,1999,27,Female,Yes,Yes,1
...,...,...,...,...,...,...,...,...,...
5221,5222,Yes,White,2000,17,Male,Yes,Yes,0
5222,5223,Yes,White,2000,21,Female,Yes,Yes,0
5223,5224,Yes,Black,1999,21,Female,Yes,Yes,1
5224,5225,No,Black,1998,24,Male,Yes,Yes,4
5225,5226,Yes,White,1999,16,Male,Yes,Yes,3

Aggregate Statistics(groupby)

In [8]:
df.groupby(['sex']).mean().sort_values('year',ascending = False)

TypeError: Could not convert YesYesYesYesNoYesYesYesYesYesYesYesYesYesYesYesNoYesYesYesYesYesYesNoYesYesYesYesYesYesNoYesYesYesNoYesYesYesYesYesNoYesYesYesYesYesYesYesYesNoYesYesNoYesYesYesYesYesYesNoYesNoNoNoYesNoYesYesYesYesNoYesNoYesYesNoYesYesYesYesYesYesYesNoNoYesNoYesYesNoYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesNoYesYesYesYesYesYesYesYesNoNoYesYesYesYesYesYesYesYesYesYesYesYesYesNoYesYesYesNoYesNoYesYesYesYesYesYesNoYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesNoYesNoYesYesYesYesYesYesYesYesYesNoYesYesNoYesYesYesYesYesYesNoYesYesYesYesYesYesYesYesYesYesYesNoNoYesYesYesYesYesYesYesYesYesYesYesYesNoYesYesYesYesYesYesYesNoYesYesNoYesYesNoYesYesYesYesYesYesYesYesYesYesYesYesYesNoYesYesYesYesNoYesNoYesYesYesYesYesYesYesYesYesYesYesYesYesYesNoYesYesYesYesNoNoYesNoYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesNoYesYesYesYesYesYesYesYesNoYesYesYesNoYesYesYesYesYesYesYesNoYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesNoYesNoYesNoNoYesNoYesYesNoYesYesYesYesYesYesYesYesYesYesNoYesYesYesYesYesYesYesNoYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesYesNoYesYesYesNoYesYesYesYesYesYesYesYesYesNoYesYesNoYesYesYesNoYesNoYesYesYesYesYesYesYesYesYesYesYesYesYes to numeric

In [9]:
df.groupby(['age']).sum()
#only want to add a new column named count and access it for convenience
df['count']=1 
df.groupby(['age']).count()['count']
#can also groupby multiple parameters
df.groupby(['age','sex']).count()['count']

age         sex
12          Male         3
13          Female       1
            Male        12
14          Female       5
            Male        54
                      ...
62          Male         1
64          Male         2
66          Male         2
Mind blown  Female     111
            Male      1377
Name: count, Length: 90, dtype: int64

Working with large amounts of data

In [11]:
for df in pd.read_csv('modified.csv',chunksize=5):
    print('Chunk df')
    print(df)

Chunk df
   Unnamed: 0 released released.1 released.2 released.3 released.4 released.5
0           1      Yes        Yes        Yes        Yes        Yes        Yes  \
1           2       No         No         No         No         No         No
2           3      Yes        Yes        Yes        Yes        Yes        Yes
3           4       No         No         No         No         No         No
4           5      Yes        Yes        Yes        Yes        Yes        Yes

  released.6 released.7 released.8  ... released.3014 released.3015
0        Yes        Yes        Yes  ...           Yes           Yes  \
1         No         No         No  ...            No            No
2        Yes        Yes        Yes  ...           Yes           Yes
3         No         No         No  ...            No            No
4        Yes        Yes        Yes  ...           Yes           Yes

  released.3016 released.3017 released.3018 released.3019 released.3020
0           Yes           Yes           Yes           Yes           Yes  \
1            No            No            No            No            No
2           Yes           Yes           Yes           Yes           Yes
3            No            No            No            No            No
4           Yes           Yes           Yes           Yes           Yes

  released.3021 released.3022 released.3023
0           Yes           Yes           Yes
1            No            No            No
2           Yes           Yes           Yes
3            No            No            No
4           Yes           Yes           Yes

[5 rows x 3025 columns]
Chunk df
   Unnamed: 0 released released.1 released.2 released.3 released.4 released.5
5           6      Yes        Yes        Yes        Yes        Yes        Yes  \
6           7      Yes        Yes        Yes        Yes        Yes        Yes
7           8      Yes        Yes        Yes        Yes        Yes        Yes
8           9      Yes        Yes        Yes        Yes        Yes        Yes
9          10      Yes        Yes        Yes        Yes        Yes        Yes

  released.6 released.7 released.8  ... released.3014 released.3015
5        Yes        Yes        Yes  ...           Yes           Yes  \
6        Yes        Yes        Yes  ...           Yes           Yes
7        Yes        Yes        Yes  ...           Yes           Yes
8        Yes        Yes        Yes  ...           Yes           Yes
9        Yes        Yes        Yes  ...           Yes           Yes

  released.3016 released.3017 released.3018 released.3019 released.3020
5           Yes           Yes           Yes           Yes           Yes  \
6           Yes           Yes           Yes           Yes           Yes
7           Yes           Yes           Yes           Yes           Yes
8           Yes           Yes           Yes           Yes           Yes
9           Yes           Yes           Yes           Yes           Yes

  released.3021 released.3022 released.3023
5           Yes           Yes           Yes
6           Yes           Yes           Yes
7           Yes           Yes           Yes
8           Yes           Yes           Yes
9           Yes           Yes           Yes

[5 rows x 3025 columns]
Chunk df
    Unnamed: 0 released released.1 released.2 released.3 released.4
10          11      Yes        Yes        Yes        Yes        Yes  \
11          12      Yes        Yes        Yes        Yes        Yes
12          13      Yes        Yes        Yes        Yes        Yes
13          14      Yes        Yes        Yes        Yes        Yes
14          15      Yes        Yes        Yes        Yes        Yes

   released.5 released.6 released.7 released.8  ... released.3014
10        Yes        Yes        Yes        Yes  ...           Yes  \
11        Yes        Yes        Yes        Yes  ...           Yes
12        Yes        Yes        Yes        Yes  ...           Yes
13        Yes        Yes        Yes        Yes  ...           Yes
14        Yes        Yes        Yes        Yes  ...           Yes

   released.3015 released.3016 released.3017 released.3018 released.3019
10           Yes           Yes           Yes           Yes           Yes  \
11           Yes           Yes           Yes           Yes           Yes
12           Yes           Yes           Yes           Yes           Yes
13           Yes           Yes           Yes           Yes           Yes
14           Yes           Yes           Yes           Yes           Yes

   released.3020 released.3021 released.3022 released.3023
10           Yes           Yes           Yes           Yes
11           Yes           Yes           Yes           Yes
12           Yes           Yes           Yes           Yes
13           Yes           Yes           Yes           Yes
14           Yes           Yes           Yes           Yes

[5 rows x 3025 columns]
Chunk df
    Unnamed: 0 released released.1 released.2 released.3 released.4
15          16      Yes        Yes        Yes        Yes        Yes  \
16          17       No         No         No         No         No
17          18       No         No         No         No         No
18          19      Yes        Yes        Yes        Yes        Yes
19          20       No         No         No         No         No

   released.5 released.6 released.7 released.8  ... released.3014
15        Yes        Yes        Yes        Yes  ...           Yes  \
16         No         No         No         No  ...            No
17         No         No         No         No  ...            No
18        Yes        Yes        Yes        Yes  ...           Yes
19         No         No         No         No  ...            No

   released.3015 released.3016 released.3017 released.3018 released.3019
15           Yes           Yes           Yes           Yes           Yes  \
16            No            No            No            No            No
17            No            No            No            No            No
18           Yes           Yes           Yes           Yes           Yes
19            No            No            No            No            No

   released.3020 released.3021 released.3022 released.3023
15           Yes           Yes           Yes           Yes
16            No            No            No            No
17            No            No            No            No
18           Yes           Yes           Yes           Yes
19            No            No            No            No

[5 rows x 3025 columns]
Chunk df
    Unnamed: 0 released released.1 released.2 released.3 released.4
20          21      Yes        Yes        Yes        Yes        Yes  \
21          22      Yes        Yes        Yes        Yes        Yes
22          23      Yes        Yes        Yes        Yes        Yes
23          24       No         No         No         No         No
24          25      Yes        Yes        Yes        Yes        Yes

   released.5 released.6 released.7 released.8  ... released.3014
20        Yes        Yes        Yes        Yes  ...           Yes  \
21        Yes        Yes        Yes        Yes  ...           Yes
22        Yes        Yes        Yes        Yes  ...           Yes
23         No         No         No         No  ...            No
24        Yes        Yes        Yes        Yes  ...           Yes

   released.3015 released.3016 released.3017 released.3018 released.3019
20           Yes           Yes           Yes           Yes           Yes  \
21           Yes           Yes           Yes           Yes           Yes
22           Yes           Yes           Yes           Yes           Yes
23            No            No            No            No            No
24           Yes           Yes           Yes           Yes           Yes

   released.3020 released.3021 released.3022 released.3023
20           Yes           Yes           Yes           Yes
21           Yes           Yes           Yes           Yes
22           Yes           Yes           Yes           Yes
23            No            No            No            No
24           Yes           Yes           Yes           Yes

[5 rows x 3025 columns]
Chunk df
    Unnamed: 0 released released.1 released.2 released.3 released.4
25          26      Yes        Yes        Yes        Yes        Yes  \
26          27      Yes        Yes        Yes        Yes        Yes
27          28      Yes        Yes        Yes        Yes        Yes
28          29      Yes        Yes        Yes        Yes        Yes
29          30      Yes        Yes        Yes        Yes        Yes

   released.5 released.6 released.7 released.8  ... released.3014
25        Yes        Yes        Yes        Yes  ...           Yes  \
26        Yes        Yes        Yes        Yes  ...           Yes
27        Yes        Yes        Yes        Yes  ...           Yes
28        Yes        Yes        Yes        Yes  ...           Yes
29        Yes        Yes        Yes        Yes  ...           Yes

   released.3015 released.3016 released.3017 released.3018 released.3019
25           Yes           Yes           Yes           Yes           Yes  \
26           Yes           Yes           Yes           Yes           Yes
27           Yes           Yes           Yes           Yes           Yes
28           Yes           Yes           Yes           Yes           Yes
29           Yes           Yes           Yes           Yes           Yes

   released.3020 released.3021 released.3022 released.3023
25           Yes           Yes           Yes           Yes
26           Yes           Yes           Yes           Yes
27           Yes           Yes           Yes           Yes
28           Yes           Yes           Yes           Yes
29           Yes           Yes           Yes           Yes

[5 rows x 3025 columns]
Chunk df
    Unnamed: 0 released released.1 released.2 released.3 released.4
30          31      Yes        Yes        Yes        Yes        Yes  \
31          32      Yes        Yes        Yes        Yes        Yes
32          33       No         No         No         No         No
33          34       No         No         No         No         No
34          35      Yes        Yes        Yes        Yes        Yes

   released.5 released.6 released.7 released.8  ... released.3014
30        Yes        Yes        Yes        Yes  ...           Yes  \
31        Yes        Yes        Yes        Yes  ...           Yes
32         No         No         No         No  ...            No
33         No         No         No         No  ...            No
34        Yes        Yes        Yes        Yes  ...           Yes

   released.3015 released.3016 released.3017 released.3018 released.3019
30           Yes           Yes           Yes           Yes           Yes  \
31           Yes           Yes           Yes           Yes           Yes
32            No            No            No            No            No
33            No            No            No            No            No
34           Yes           Yes           Yes           Yes           Yes

   released.3020 released.3021 released.3022 released.3023
30           Yes           Yes           Yes           Yes
31           Yes           Yes           Yes           Yes
32            No            No            No            No
33            No            No            No            No
34           Yes           Yes           Yes           Yes

[5 rows x 3025 columns]
Chunk df
    Unnamed: 0 released released.1 released.2 released.3 released.4
35          36      Yes        Yes        Yes        Yes        Yes  \
36          37      Yes        Yes        Yes        Yes        Yes
37          38      Yes        Yes        Yes        Yes        Yes
38          39       No         No         No         No         No
39          40       No         No         No         No         No

   released.5 released.6 released.7 released.8  ... released.3014
35        Yes        Yes        Yes        Yes  ...           Yes  \
36        Yes        Yes        Yes        Yes  ...           Yes
37        Yes        Yes        Yes        Yes  ...           Yes
38         No         No         No         No  ...            No
39         No         No         No         No  ...            No

   released.3015 released.3016 released.3017 released.3018 released.3019
35           Yes           Yes           Yes           Yes           Yes  \
36           Yes           Yes           Yes           Yes           Yes
37           Yes           Yes           Yes           Yes           Yes
38            No            No            No            No            No
39            No            No            No            No            No

   released.3020 released.3021 released.3022 released.3023
35           Yes           Yes           Yes           Yes
36           Yes           Yes           Yes           Yes
37           Yes           Yes           Yes           Yes
38            No            No            No            No
39            No            No            No            No

[5 rows x 3025 columns]
Chunk df
    Unnamed: 0 released released.1 released.2 released.3 released.4
40          41      Yes        Yes        Yes        Yes        Yes  \
41          42      Yes        Yes        Yes        Yes        Yes
42          43      Yes        Yes        Yes        Yes        Yes
43          44      Yes        Yes        Yes        Yes        Yes
44          45      Yes        Yes        Yes        Yes        Yes

   released.5 released.6 released.7 released.8  ... released.3014
40        Yes        Yes        Yes        Yes  ...           Yes  \
41        Yes        Yes        Yes        Yes  ...           Yes
42        Yes        Yes        Yes        Yes  ...           Yes
43        Yes        Yes        Yes        Yes  ...           Yes
44        Yes        Yes        Yes        Yes  ...           Yes

   released.3015 released.3016 released.3017 released.3018 released.3019
40           Yes           Yes           Yes           Yes           Yes  \
41           Yes           Yes           Yes           Yes           Yes
42           Yes           Yes           Yes           Yes           Yes
43           Yes           Yes           Yes           Yes           Yes
44           Yes           Yes           Yes           Yes           Yes

   released.3020 released.3021 released.3022 released.3023
40           Yes           Yes           Yes           Yes
41           Yes           Yes           Yes           Yes
42           Yes           Yes           Yes           Yes
43           Yes           Yes           Yes           Yes
44           Yes           Yes           Yes           Yes

[5 rows x 3025 columns]
Chunk df
    Unnamed: 0 released released.1 released.2 released.3 released.4
45          46       No         No         No         No         No  \
46          47      Yes        Yes        Yes        Yes        Yes
47          48      Yes        Yes        Yes        Yes        Yes
48          49      Yes        Yes        Yes        Yes        Yes
49          50       No         No         No         No         No

   released.5 released.6 released.7 released.8  ... released.3014
45         No         No         No         No  ...            No  \
46        Yes        Yes        Yes        Yes  ...           Yes
47        Yes        Yes        Yes        Yes  ...           Yes
48        Yes        Yes        Yes        Yes  ...           Yes
49         No         No         No         No  ...            No

   released.3015 released.3016 released.3017 released.3018 released.3019
45            No            No            No            No            No  \
46           Yes           Yes           Yes           Yes           Yes
47           Yes           Yes           Yes           Yes           Yes
48           Yes           Yes           Yes           Yes           Yes
49            No            No            No            No            No

   released.3020 released.3021 released.3022 released.3023
45            No            No            No            No
46           Yes           Yes           Yes           Yes
47           Yes           Yes           Yes           Yes
48           Yes           Yes           Yes           Yes
49            No            No            No            No

[5 rows x 3025 columns]
Chunk df
    Unnamed: 0 released released.1 released.2 released.3 released.4
50          51      Yes        Yes        Yes        Yes        Yes  \
51          52      Yes        Yes        Yes        Yes        Yes
52          53      Yes        Yes        Yes        Yes        Yes
53          54      Yes        Yes        Yes        Yes        Yes
54          55      Yes        Yes        Yes        Yes        Yes

   released.5 released.6 released.7 released.8  ... released.3014
50        Yes        Yes        Yes        Yes  ...           Yes  \
51        Yes        Yes        Yes        Yes  ...           Yes
52        Yes        Yes        Yes        Yes  ...           Yes
53        Yes        Yes        Yes        Yes  ...           Yes
54        Yes        Yes        Yes        Yes  ...           Yes

   released.3015 released.3016 released.3017 released.3018 released.3019
50           Yes           Yes           Yes           Yes           Yes  \
51           Yes           Yes           Yes           Yes           Yes
52           Yes           Yes           Yes           Yes           Yes
53           Yes           Yes           Yes           Yes           Yes
54           Yes           Yes           Yes           Yes           Yes

   released.3020 released.3021 released.3022 released.3023
50           Yes           Yes           Yes           Yes
51           Yes           Yes           Yes           Yes
52           Yes           Yes           Yes           Yes
53           Yes           Yes           Yes           Yes
54           Yes           Yes           Yes           Yes

[5 rows x 3025 columns]
Chunk df
    Unnamed: 0 released released.1 released.2 released.3 released.4
55          56      Yes        Yes        Yes        Yes        Yes  \
56          57      Yes        Yes        Yes        Yes        Yes
57          58      Yes        Yes        Yes        Yes        Yes
58          59      Yes        Yes        Yes        Yes        Yes
59          60      Yes        Yes        Yes        Yes        Yes

   released.5 released.6 released.7 released.8  ... released.3014
55        Yes        Yes        Yes        Yes  ...           Yes  \
56        Yes        Yes        Yes        Yes  ...           Yes
57        Yes        Yes        Yes        Yes  ...           Yes
58        Yes        Yes        Yes        Yes  ...           Yes
59        Yes        Yes        Yes        Yes  ...           Yes

   released.3015 released.3016 released.3017 released.3018 released.3019
55           Yes           Yes           Yes           Yes           Yes  \
56           Yes           Yes           Yes           Yes           Yes
57           Yes           Yes           Yes           Yes           Yes
58           Yes           Yes           Yes           Yes           Yes
59           Yes           Yes           Yes           Yes           Yes

   released.3020 released.3021 released.3022 released.3023
55           Yes           Yes           Yes           Yes
56           Yes           Yes           Yes           Yes
57           Yes           Yes           Yes           Yes
58           Yes           Yes           Yes           Yes
59           Yes           Yes           Yes           Yes

[5 rows x 3025 columns]
Chunk df
    Unnamed: 0 released released.1 released.2 released.3 released.4
60          61      Yes        Yes        Yes        Yes        Yes  \
61          62      Yes        Yes        Yes        Yes        Yes
62          63      Yes        Yes        Yes        Yes        Yes